name: speakeasy
description: Speakeasy Privacy Suite (template)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO: add:
  # flutter_secure_storage
  # cryptography
  # drift + sqlcipher (android)
  # http / dio
  # uuid
  # app_links
  # local_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
